/**
 * Inline the ext-apps browser bundle into each widget HTML file and emit
 * src/generated/widgets.ts.
 *
 * Widgets run in a sandboxed iframe whose CSP blocks CDN script fetches, so the
 * @modelcontextprotocol/ext-apps runtime must be inlined into the HTML. The npm
 * bundle is an ES module ending in `export{a as B,...};` — we rewrite that export
 * statement to a `globalThis.ExtApps = {...}` assignment so it works from a plain
 * inline <script type="module"> without imports.
 *
 * Runs on Node at build time (Workers have no fs), before wrangler dev/deploy,
 * tsc, and vitest.
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(import.meta.url);

const bundle = readFileSync(
	require.resolve("@modelcontextprotocol/ext-apps/app-with-deps"),
	"utf8",
).replace(/export\{([^}]+)\};?\s*$/, (_match, body) => {
	const entries = body.split(",").map((part) => {
		const [local, exported] = part.split(" as ").map((s) => s.trim());
		return `${exported ?? local}:${local}`;
	});
	return `globalThis.ExtApps={${entries.join(",")}};`;
});

const widgetsDir = join(root, "widgets");
const entries = {};
for (const file of readdirSync(widgetsDir)) {
	if (!file.endsWith(".html")) continue;
	const html = readFileSync(join(widgetsDir, file), "utf8");
	if (!html.includes("/*__EXT_APPS_BUNDLE__*/")) {
		throw new Error(`${file} is missing the /*__EXT_APPS_BUNDLE__*/ placeholder`);
	}
	entries[basename(file, ".html")] = html.replace("/*__EXT_APPS_BUNDLE__*/", () => bundle);
}

const names = Object.keys(entries);
if (names.length === 0) throw new Error("No widget HTML files found in widgets/");

const output = `// Generated by scripts/build-widgets.mjs — do not edit.
export const widgets: Record<${names.map((n) => JSON.stringify(n)).join(" | ")}, string> = ${JSON.stringify(entries)};
`;

mkdirSync(join(root, "src/generated"), { recursive: true });
writeFileSync(join(root, "src/generated/widgets.ts"), output);
console.log(
	`build-widgets: inlined ${names.join(", ")} (${(output.length / 1024).toFixed(0)} KiB)`,
);
